apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-main
  template:
    metadata:
      labels:
        app: frontend-main
    spec:
      containers:
        - name: frontend-main
          image: frontend-main
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
